// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc2974.Testbed;

import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc2974.Testbed.commands.*;
import org.usfirst.frc2974.Testbed.subsystems.*;

import edu.wpi.first.wpilibj.GamepadBase;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.Button;
import edu.wpi.first.wpilibj.buttons.JoystickButton;

/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {

	public Joystick left;
	public Joystick right;
	public Gamepad gamepad;

	public Button shiftUp;
	public Button shiftDown;
	public Button shiftUpAlt;
	public Button shiftDownAlt;

	public Button shoot;

	public Button intake;
	public Button outtake;
	public Button stoptake;
	public Button dumptake;

	public Button hopperControl;
	public Button hopperAltControl;
	public Button aimOverride;
	public Button atSpeed;

	public OI() {
		right = new Joystick(1);
		left = new Joystick(0);
		gamepad = new Gamepad(2);

		shiftUp = new JoystickButton(left, 3);
		shiftDown = new JoystickButton(left, 2);
		shiftUpAlt = new JoystickButton(left, 11);
		shiftDownAlt = new JoystickButton(left, 10);

		shoot = new JoystickButton(left, 1);

		intake = new JoystickButton(gamepad, 1);
		outtake = new JoystickButton(gamepad, 3);
		stoptake = new JoystickButton(gamepad, 2);
		dumptake = new JoystickButton(gamepad, 4);

		hopperControl = new JoystickButton(right, 1);
		hopperAltControl = new JoystickButton(gamepad, 8);

		aimOverride = new JoystickButton(right, 7);
		atSpeed = new JoystickButton(right, 6);
	}

	public boolean startHold() {
		return gamepad.getRawButton(7);
	}

	public boolean endHold() {
		return gamepad.getRawButton(5);
	}

	public boolean startClimb() {
		return gamepad.getRawButton(5);
	}

	public double climbY() {
		return gamepad.getLeftY();
	}
}
