// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc2974.Robot2017;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Talon;

import com.ctre.talonsrx.CANTalon;

import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.DigitalOutput;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.Spark;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
	public static Talon left;
	public static Talon right;
	public static Talon indexer;
	public static Talon intake;
	public static Spark climber;

	public static com.ctre.talonsrx.CANTalon flywheelMotor;

	public static Encoder encoderLeft;
	public static Encoder encoderRight;
	public static Encoder encoderFlyWheel;

	public static Compressor compressor;
	public static Solenoid pneumaticsShifter;
	public static Solenoid hopperRelease;

	public static DigitalInput laser;

	public static void init() {
		left = new Talon(0);
		right = new Talon(1);
		indexer = new Talon(2);
		intake = new Talon(3);
		flywheelMotor = new CANTalon(2);

		compressor = new Compressor();
		pneumaticsShifter = new Solenoid(0);
		hopperRelease = new Solenoid(1);

		encoderRight = new Encoder(new DigitalInput(0), new DigitalInput(1));
		encoderLeft = new Encoder(new DigitalInput(2), new DigitalInput(3));
		encoderFlyWheel = new Encoder(new DigitalInput(4), new DigitalInput(5));

		// laser = new DigitalInput();
	}
}
